server:
    port: 9196

tenants:
  datasources:
    tenant1:
      jdbcUrl: jdbc:mysql://localhost:3306/patientDb3?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: Balaji@407
      schema: tenat1schema
    tenant2:
      jdbcUrl: jdbc:mysql://localhost:3306/patientDb3?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: Balaji@407
      schema: tenat2schema
default:
     tenant: patientDb1
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
