server:
    port: 9196

tenants:
  datasources:
    tenant1:
      jdbcUrl: jdbc:postgresql://localhost:5432/patientdb4
      driverClassName: org.postgresql.Driver
      username: postgres
      password: Balaji@407
      schema: tenant1
    tenant2:
      jdbcUrl: jdbc:postgresql://localhost:5432/patientdb4
      driverClassName: org.postgresql.Driver
      username: postgres
      password: Balaji@407
      schema: tenant2
spring:
  jpa:
  properties:
      hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            temp:
              use_jdbc_metadata_defaults: false
