server:
    port: 9196

tenants:
  datasources:
    tenant1:
      jdbcUrl: jdbc:postgresql://localhost:5432/patientdb4
      driverClassName: org.postgresql.Driver
      username: ${username}
      password: ${password}
      schema: ${schema}
    tenant2:
      jdbcUrl: jdbc:postgresql://localhost:5432/patientdb4
      driverClassName: org.postgresql.Driver
      username: ${username}
      password: ${password}
      schema: ${schema}
spring:
  jpa:
  properties:
      hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            temp:
              use_jdbc_metadata_defaults: false
